version: '3.9'
services:
  # Apache webserver service
  webserver:
    container_name: PHP-webServer
    build:
    # Dockerfile path
      context: .
      dockerfile: Dockerfile  
    # Mount the local ./app directory to /var/www/html in the container
    volumes:
      - ./:/var/www/html 
    # Map port 8000 on the host to port 80 on the container 
    ports:
      - 8000:80   